# Imports

In [7]:
import pandas as pd
import numpy as np
from sklearn import datasets

# Function definitions

In [8]:
def standardize(a):
    return (a - np.mean(a)) / np.std(a)

# Loading wine dataset and checking if attributes are standardized

In [9]:
wine = datasets.load_wine()
wine_data = wine.data
wine_target = wine.target
print(np.mean(wine_data, axis = 0))
print(np.std(wine_data, axis = 0))

[1.30006180e+01 2.33634831e+00 2.36651685e+00 1.94949438e+01
 9.97415730e+01 2.29511236e+00 2.02926966e+00 3.61853933e-01
 1.59089888e+00 5.05808988e+00 9.57449438e-01 2.61168539e+00
 7.46893258e+02]
[8.09542915e-01 1.11400363e+00 2.73572294e-01 3.33016976e+00
 1.42423077e+01 6.24090564e-01 9.96048950e-01 1.24103260e-01
 5.70748849e-01 2.31176466e+00 2.27928607e-01 7.07993265e-01
 3.14021657e+02]


# Standardizing the attributes

In [10]:
wine_data_std = np.apply_along_axis(standardize, 0, wine_data)
print(np.mean(wine_data_std, axis = 0))
print(np.std(wine_data_std, axis = 0))

[-8.38280756e-16 -1.19754394e-16 -8.37033314e-16 -3.99181312e-17
 -3.99181312e-17  0.00000000e+00 -3.99181312e-16  3.59263181e-16
 -1.19754394e-16  2.49488320e-17  1.99590656e-16  3.19345050e-16
 -1.59672525e-16]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# Loading iris dataset and checking if attributes are standardized

In [11]:
iris = datasets.load_iris()
iris_data = iris.data
iris_target = iris.target
print(np.mean(iris_data, axis = 0))
print(np.std(iris_data, axis = 0))

[5.84333333 3.05733333 3.758      1.19933333]
[0.82530129 0.43441097 1.75940407 0.75969263]


# Standardizing the attributes

In [12]:
iris_data_std = np.apply_along_axis(standardize, 0, iris_data)
print(np.mean(iris_data_std, axis = 0))
print(np.std(iris_data_std, axis = 0))

[-4.73695157e-16 -7.81597009e-16 -4.26325641e-16 -4.73695157e-16]
[1. 1. 1. 1.]
